name: CI/CD with Gradle

# main 브랜치에 push되면 실행
on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_HUB_REGISTRY : ${{ secrets.DOCKER_REGISTRY }}
      APPLICATION_YML : ${{ secrets.APPLICATION_YML }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout GitHub Repository # 레포 코드 가져오기
        uses: actions/checkout@v4

      - name: Set up JDK 17 # jdk 17 다운
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ env.APPLICATION_YML }}" > src/main/resources/application.yml

      # gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 빌드(test는 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      - name: Check Docker Username
        run: echo "${{ env.DOCKER_HUB_USERNAME }}"

      # docker image build
      - name: Docker image build
        run: docker build -t ${{ env.DOCKER_HUB_REGISTRY }}/app:${{ env.IMAGE_TAG }} .

      # DockerHub 로그인
      - name: DockerHub Login
        run: echo "${{ env.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin

      # Docker image push
      - name: Docker image push
        run: docker push ${{ env.DOCKER_HUB_REGISTRY }}/app:${{ env.IMAGE_TAG }}

  cd:
    needs: ci
    name: CD
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME : ${{ secrets.DOCKER_USERNAME }}
      DOCKER_HUB_PASSWORD : ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_HUB_REGISTRY : ${{ secrets.DOCKER_REGISTRY }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      #
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" > /home/ubuntu/.env
            echo "DOCKER_HUB_USERNAME=${{ env.DOCKER_HUB_USERNAME }}" >> /home/ubuntu/.env
            echo "DOCKER_HUB_PASSWORD=${{ env.DOCKER_HUB_PASSWORD }}" >> /home/ubuntu/.env
            echo "DOCKER_HUB_REGISTRY=${{ env.DOCKER_HUB_REGISTRY }}" >> /home/ubuntu/.env
            cd /home/ubuntu/script
            ./deploy.sh